CREATE TABLE adaptivepomodoro.L_USUARIOS (
	ID_USER 				INT 			AUTO_INCREMENT PRIMARY KEY,
    USUARIO					VARCHAR(255)	NOT NULL,
    NOMBRE_USUARIO 			TEXT			NOT NULL,
    PASSWORD				TEXT			NOT NULL,
   
    UNIQUE KEY UK_L_USUARIOS_USUARIO (USUARIO)
);