CREATE TABLE adaptivepomodoro.M_POMODORO (
	ID_USER 				INT 			NOT NULL,
    ID_ESTADO				INT	            NOT NULL,
    POMODORO 			    DECIMAL(4,2)	NOT NULL,
   
    PRIMARY KEY (ID_USER, ID_ESTADO),
	CONSTRAINT FK_M_POMODORO_L_USUARIOS
        FOREIGN KEY (ID_USER)
        REFERENCES adaptivepomodoro.L_USUARIOS (ID_USER)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT FK_M_POMODORO_L_ESTADO_ANIMO
        FOREIGN KEY (ID_ESTADO)
        REFERENCES adaptivepomodoro.L_ESTADO_ANIMO (ID_ESTADO)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);