CREATE TABLE adaptivepomodoro.M_TIEMPOS (
	ID_USER 				INT				NOT NULL,
    FECHA					DATETIME		NOT NULL,
    TIEMPO		 			INT				NOT NULL,
   
	PRIMARY KEY (ID_USER, FECHA),
	CONSTRAINT FK_M_TIEMPOS_L_USUARIOS
        FOREIGN KEY (ID_USER)
        REFERENCES adaptivepomodoro.L_USUARIOS (ID_USER)
        ON UPDATE CASCADE
        ON DELETE CASCADE

);